### PR TITLE
Removing Vulnerabilities and pointing to latest released codebase of nats-io

### PR DESCRIPTION
**Pull request by shantanubansal**

### CODE REVIEW

**Comment by shantanubansal** [comment]
@wallyqs Can you please help here?
Updating dependencies and pointing dependencies to use latest released code from nats.io.
Also Upgraded the golang version.

Current nats-account-resolver is not compatible with nats-io/jwt/v2 so updated the entire dependecies

**Review by aricart — DISMISSED** [review]
LGTM

**Review by aricart — COMMENTED** [review]
Actually this is not LGTM - the tests are removing a core feature which is handling of v1 jwts

**Comment by aricart** [comment]
I will update to the current deps, but the fix you seek for vulnerabilities is simply because tools are incorrectly saying the the jwt lib has an issue - we are releasing this soon.

**Pull request closed without merging**
